name: Cross-platform Tests

on:
  workflow_dispatch:
    inputs:
      ref:
        description: Git ref to check out for testing
        required: false
        default: master
        type: string
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - reopened
  push:
    branches:
      - main
      - master
      - develop
  workflow_call:
    inputs:
      ref:
        description: Git ref to check out for testing
        required: false
        type: string

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    if: >-
      ${{
        inputs.ref != '' ||
        (github.event_name == 'push' &&
          !(startsWith(github.event.head_commit.message, 'Prepare v') &&
            endsWith(github.event.head_commit.message, ' release'))) ||
        (github.event_name == 'pull_request' &&
          contains(github.event.pull_request.labels.*.name, 'ready to merge'))
      }}
    runs-on: ${{ matrix.os }}
    name: test ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.ref != '' && inputs.ref || github.ref }}
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: cargo generate-lockfile
        if: hashFiles('Cargo.lock') == ''
        run: cargo generate-lockfile
      - name: cargo test --locked
        run: cargo test --locked --all-features --all-targets
      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2
